addons:
  sonarcloud:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
    github_token:
      secure: "$GH_TOKEN"
    branches:
      - /.*/
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'
language: node_js
node_js:
  - 10
before_script:
  - npm prune
script: npm test
after_success:
  - npm run security:snyk:all
after_script:
   - sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN -X
  #  - 'cat ./coverage/lcov.info | coveralls'
