dist: trusty
addons:
  sonarcloud:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
    - '$HOME/.sonar/cache'
language: node_js
node_js:
  - 10
before_script:
  - npm prune
  - npm dedupe
script: npm test
after_success:
  - npm run security:snyk:all
after_script:
   - sonar-scanner -Dsonar.projectKey=commonality_archetypes -Dsonar.organization=commonality -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$COMMONALITY_SONAR_TOKEN
